version: '2'
services:
    comprehendservice-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/ComprehendService/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ComprehendService
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
